
<label for="from-tmaln" class="label-tmaln"><?php echo Mage::helper('ajaxnavigation')->__('From') ?></label>
<input type="text" id="from-price-range" class="input-tmaln" value="<?php echo $this->getMinPrice() ?>"/>
<label for="to-tmaln" class="label-tmaln"><?php echo Mage::helper('ajaxnavigation')->__('To') ?></label>
<input type="text" id="to-price-range" class="input-tmaln" value="<?php echo $this->getMaxPrice() ?>"/>

<div id="slider-range"></div>
