<?php $_productCollection = $this->getProductCollection(); ?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php if(!$_productCollection->count()): ?>
	<?php echo $this->__('There are no products matching the selection.') ?>
<?php else: ?>
	<?php foreach ($_productCollection as $_product) { ?>
	
		<ul class="pop_item">
			<li class="image"><a title="<?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?>" href="<?php echo $_product->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(60, 100); ?>" alt="<?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?>" /></a></li>
			<li class="title"><a title="<?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?>" href="<?php echo $_product->getProductUrl() ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></li>
		</ul>
		
	<?php } ?>
<?php endif;?>