<?php
/**
 * Magento
 *
 * @category    design
 * @package     insales_default
 * @copyright   Copyright (c) 2013 Magazento. (http://www.magazento.com)
 *
 *
 *
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>">    
    <head>
        <?php echo $this->getChildHtml('head') ?>
    </head>
    <body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
        <?php echo $this->getChildHtml('after_body_start') ?>
        <div class="wrapper">
            <?php echo $this->getChildHtml('global_notices') ?>
            <div class="page">
                <?php echo $this->getChildHtml('header') ?>
                <?php echo $this->getChildHtml('breadcrumbs') ?>      
                <div class="main-container col2-left-layout container_16">
                    <div class="grid_16">                       
                        <div class="main">                
                            <div class="grid_4 alpha">
                                <aside class="col-left sidebar">
                                    <?php echo $this->getChildHtml('left') ?>
                                </aside>
                            </div>
                            <div class="grid_12 omega">
                                <div class="col-main">
                                    <?php echo $this->getChildHtml('global_messages') ?>
                                    <?php echo $this->getChildHtml('content') ?>
                                </div>                        
                            </div>                        
                        </div>                        
                    </div>                        
                </div>
                <?php echo $this->getChildHtml('footer') ?>
                <?php echo $this->getChildHtml('before_body_end') ?>
            </div>
        </div>
        <?php echo $this->getAbsoluteFooter() ?>
    </body>
</html>
